"""Action vocabulary for the full NetHack wrapper.

The names are intentionally stable and model-facing.  They map to NetHack key
codes in the NLE fork's ``nle.glyphbench_wrapper`` backend at runtime.
"""

from __future__ import annotations

from glyphbench.core.action import ActionSpec

NETHACK_ACTION_SPEC = ActionSpec(
    names=(
        "MOVE_N",
        "MOVE_E",
        "MOVE_S",
        "MOVE_W",
        "MOVE_NE",
        "MOVE_SE",
        "MOVE_SW",
        "MOVE_NW",
        "RUN_N",
        "RUN_E",
        "RUN_S",
        "RUN_W",
        "RUN_NE",
        "RUN_SE",
        "RUN_SW",
        "RUN_NW",
        "GO_UP",
        "GO_DOWN",
        "WAIT",
        "MORE",
        "EXTCMD",
        "EXTLIST",
        "ADJUST",
        "ANNOTATE",
        "APPLY",
        "ATTRIBUTES",
        "AUTOPICKUP",
        "CALL",
        "CAST",
        "CHAT",
        "CLOSE",
        "CONDUCT",
        "DIP",
        "DROP",
        "DROPTYPE",
        "EAT",
        "ENGRAVE",
        "ENHANCE",
        "ESC",
        "FIGHT",
        "FIRE",
        "FORCE",
        "GLANCE",
        "HISTORY",
        "INVENTORY",
        "INVENTTYPE",
        "INVOKE",
        "JUMP",
        "KICK",
        "KNOWN",
        "KNOWNCLASS",
        "LOOK",
        "LOOT",
        "MONSTER",
        "MOVE",
        "MOVEFAR",
        "OFFER",
        "OPEN",
        "OPTIONS",
        "OVERVIEW",
        "PAY",
        "PICKUP",
        "PRAY",
        "PUTON",
        "QUAFF",
        "QUIT",
        "QUIVER",
        "READ",
        "REDRAW",
        "REMOVE",
        "RIDE",
        "RUB",
        "RUSH",
        "RUSH2",
        "SAVE",
        "SEARCH",
        "SEEALL",
        "SEEAMULET",
        "SEEARMOR",
        "SEEGOLD",
        "SEERINGS",
        "SEESPELLS",
        "SEETOOLS",
        "SEETRAP",
        "SEEWEAPON",
        "SHELL",
        "SIT",
        "SWAP",
        "TAKEOFF",
        "TAKEOFFALL",
        "TELEPORT",
        "THROW",
        "TIP",
        "TRAVEL",
        "TURN",
        "TWOWEAPON",
        "UNTRAP",
        "VERSION",
        "VERSIONSHORT",
        "WEAR",
        "WHATDOES",
        "WHATIS",
        "WIELD",
        "WIPE",
        "ZAP",
        "TEXT_SPACE",
        "TEXT_APOSTROPHE",
        "TEXT_QUOTE",
        "TEXT_PLUS",
        "TEXT_MINUS",
        "TEXT_DOLLAR",
        "TEXT_0",
        "TEXT_1",
        "TEXT_2",
        "TEXT_3",
        "TEXT_4",
        "TEXT_5",
        "TEXT_6",
        "TEXT_7",
        "TEXT_8",
        "TEXT_9",
    ),
    descriptions=(
        "move one cell north; also sends the 'k' key",
        "move one cell east; also sends the 'l' key",
        "move one cell south; also sends the 'j' key",
        "move one cell west; also sends the 'h' key",
        "move one cell northeast; also sends the 'u' key",
        "move one cell southeast; also sends the 'n' key, including no-answer prompts",
        "move one cell southwest; also sends the 'b' key",
        "move one cell northwest; also sends the 'y' key, including yes-answer prompts",
        "run north until interrupted",
        "run east until interrupted",
        "run south until interrupted",
        "run west until interrupted",
        "run northeast until interrupted",
        "run southeast until interrupted",
        "run southwest until interrupted",
        "run northwest until interrupted",
        "go up stairs",
        "go down stairs",
        "wait/rest for one move",
        "advance a --More-- message",
        "start an extended # command",
        "list extended commands",
        "adjust inventory letters",
        "annotate the current level",
        "apply or use a tool",
        "show character attributes",
        "toggle autopickup",
        "name an item or monster",
        "cast a spell",
        "chat with an adjacent creature",
        "close a door",
        "show conduct history",
        "dip an object into something",
        "drop an item",
        "drop selected item types",
        "eat food",
        "engrave on the floor",
        "advance or review skills",
        "cancel the current prompt or menu",
        "force a melee attack",
        "fire ammunition from the quiver",
        "force a lock",
        "inspect a map symbol",
        "show game history",
        "open inventory",
        "show inventory by item type",
        "invoke an object's power",
        "jump",
        "kick",
        "show discovered object types",
        "show one discovered object class",
        "look at the current square",
        "loot a container",
        "use a monster ability",
        "move without picking up items or attacking",
        "run without picking up items or attacking",
        "offer a sacrifice",
        "open a door",
        "show or change options",
        "show dungeon overview",
        "pay a shop bill",
        "pick up items on the current square",
        "pray",
        "put on a ring or amulet",
        "drink a potion",
        "quit the current game",
        "select quiver ammunition",
        "read a scroll or spellbook",
        "redraw the screen",
        "remove a ring or amulet",
        "mount or dismount",
        "rub a lamp or stone",
        "rush until something interesting is seen",
        "alternate rush command",
        "save and exit the game",
        "search nearby squares",
        "show all worn or wielded equipment",
        "show the worn amulet",
        "show worn armor",
        "count carried gold",
        "show worn rings",
        "show known spells",
        "show tools in use",
        "show an adjacent trap type",
        "show wielded weapon",
        "attempt a shell escape",
        "sit down",
        "swap wielded weapons",
        "take off one armor piece",
        "remove all armor",
        "teleport if the command is available",
        "throw an item",
        "empty a container",
        "travel to a map location",
        "turn undead",
        "toggle two-weapon combat",
        "untrap something",
        "show compile-time version information",
        "show short version information",
        "wear armor",
        "ask what a command does",
        "ask what a map symbol means",
        "wield a weapon",
        "wipe your face",
        "zap a wand",
        "send a literal space key",
        "send a literal apostrophe key",
        "send a literal double-quote key",
        "send a literal plus key",
        "send a literal minus key",
        "send a literal dollar key",
        "send digit 0",
        "send digit 1",
        "send digit 2",
        "send digit 3",
        "send digit 4",
        "send digit 5",
        "send digit 6",
        "send digit 7",
        "send digit 8",
        "send digit 9",
    ),
    extra_aliases={
        "ASCEND": "GO_UP",
        "DESCEND": "GO_DOWN",
        "MOVE_UP": "MOVE_N",
        "MOVE_RIGHT": "MOVE_E",
        "MOVE_DOWN": "MOVE_S",
        "MOVE_LEFT": "MOVE_W",
        "PICK_UP": "PICKUP",
        "CANCEL": "ESC",
        "SPACE": "TEXT_SPACE",
        "YES": "MOVE_NW",
        "NO": "MOVE_SE",
    },
)
