"""Craftax suite - importing registers all envs."""

from glyphbench.core.registry import register_env
from glyphbench.envs.craftax.subtasks import (
    CraftaxChopTreesEnv,
    CraftaxCraftChainEnv,
    CraftaxCraftPickaxeEnv,
    CraftaxCraftSwordEnv,
    CraftaxDungeonClearEnv,
    CraftaxDungeonExploreEnv,
    CraftaxFightZombieEnv,
    CraftaxGatherResourcesEnv,
    CraftaxMineStoneEnv,
    CraftaxSurviveHordeEnv,
)
from glyphbench.envs.craftax.subtasks_extended import (
    CraftaxBossFightEnv,
    CraftaxBowKiteEnv,
    CraftaxBowKiteHardEnv,
    CraftaxBuildShelterEnv,
    CraftaxClearFloor8GateEnv,
    CraftaxCraftIronSetEnv,
    CraftaxDarkAmbushEnv,
    CraftaxDescentGauntletEnv,
    CraftaxDiamondBootstrapEnv,
    CraftaxDiamondGearDescendEnv,
    CraftaxDungeonEnv,
    CraftaxEnchantChoiceEnv,
    CraftaxEnchantWeaponEnv,
    CraftaxFightArchersEnv,
    CraftaxFightBatsEnv,
    CraftaxFightCowEnv,
    CraftaxFightSkeletonsEnv,
    CraftaxFightSpidersEnv,
    CraftaxFightZombiesEnv,
    CraftaxFindDiamondEnv,
    CraftaxFindWaterEnv,
    CraftaxFireRealmEnv,
    CraftaxFirstDayEnv,
    CraftaxFloorClear9HpEnv,
    CraftaxGnomishMinesEnv,
    CraftaxIceRealmEnv,
    CraftaxIronBootstrapEnv,
    CraftaxKiteSkeletonsEnv,
    CraftaxLearnSpellEnv,
    CraftaxMineIronEnv,
    CraftaxNecromancerEnv,
    CraftaxNightHordeNoShelterEnv,
    CraftaxPlantFarmEnv,
    CraftaxPotionIdStakesEnv,
    CraftaxPotionTriageEnv,
    CraftaxReachDungeonEnv,
    CraftaxSewersEnv,
    CraftaxSpeedrunEnv,
    CraftaxSpellOnlyKillEnv,
    CraftaxSurfaceToIronDescendEnv,
    CraftaxSurviveHungerEnv,
    CraftaxSurviveNightEnv,
    CraftaxSurviveNightHardEnv,
    CraftaxSurviveThirstEnv,
    CraftaxSurviveWildEnv,
    CraftaxTorchDescendEnv,
    CraftaxTrollMinesEnv,
    CraftaxVaultsEnv,
    CraftaxWaveDefenseEnv,
    CraftaxXpAttributeSpendEnv,
)

_REGISTRATIONS = {
    "glyphbench/craftax-choptrees-v0": CraftaxChopTreesEnv,
    "glyphbench/craftax-minestone-v0": CraftaxMineStoneEnv,
    "glyphbench/craftax-gatherresources-v0": CraftaxGatherResourcesEnv,
    "glyphbench/craftax-craftpickaxe-v0": CraftaxCraftPickaxeEnv,
    "glyphbench/craftax-craftsword-v0": CraftaxCraftSwordEnv,
    "glyphbench/craftax-craftchain-v0": CraftaxCraftChainEnv,
    "glyphbench/craftax-fightzombie-v0": CraftaxFightZombieEnv,
    "glyphbench/craftax-survivehorde-v0": CraftaxSurviveHordeEnv,
    "glyphbench/craftax-dungeonexplore-v0": CraftaxDungeonExploreEnv,
    "glyphbench/craftax-dungeonclear-v0": CraftaxDungeonClearEnv,
    # Extended subtasks
    "glyphbench/craftax-dungeon-v0": CraftaxDungeonEnv,
    "glyphbench/craftax-gnomish-mines-v0": CraftaxGnomishMinesEnv,
    "glyphbench/craftax-sewers-v0": CraftaxSewersEnv,
    "glyphbench/craftax-vaults-v0": CraftaxVaultsEnv,
    "glyphbench/craftax-troll-mines-v0": CraftaxTrollMinesEnv,
    "glyphbench/craftax-fire-realm-v0": CraftaxFireRealmEnv,
    "glyphbench/craftax-ice-realm-v0": CraftaxIceRealmEnv,
    "glyphbench/craftax-necromancer-v0": CraftaxNecromancerEnv,
    "glyphbench/craftax-bossfight-v0": CraftaxBossFightEnv,
    "glyphbench/craftax-learn-spell-v0": CraftaxLearnSpellEnv,
    "glyphbench/craftax-enchant-weapon-v0": CraftaxEnchantWeaponEnv,
    "glyphbench/craftax-bow-kite-v0": CraftaxBowKiteEnv,
    "glyphbench/craftax-potion-triage-v0": CraftaxPotionTriageEnv,
    "glyphbench/craftax-survive-hunger-v0": CraftaxSurviveHungerEnv,
    "glyphbench/craftax-survive-thirst-v0": CraftaxSurviveThirstEnv,
    "glyphbench/craftax-survive-night-v0": CraftaxSurviveNightEnv,
    "glyphbench/craftax-survive-wild-v0": CraftaxSurviveWildEnv,
    "glyphbench/craftax-fight-cow-v0": CraftaxFightCowEnv,
    "glyphbench/craftax-fight-zombies-v0": CraftaxFightZombiesEnv,
    "glyphbench/craftax-fight-skeletons-v0": CraftaxFightSkeletonsEnv,
    "glyphbench/craftax-fight-archers-v0": CraftaxFightArchersEnv,
    "glyphbench/craftax-fight-spiders-v0": CraftaxFightSpidersEnv,
    "glyphbench/craftax-fight-bats-v0": CraftaxFightBatsEnv,
    "glyphbench/craftax-craft-ironset-v0": CraftaxCraftIronSetEnv,
    "glyphbench/craftax-mine-iron-v0": CraftaxMineIronEnv,
    "glyphbench/craftax-iron-bootstrap-v0": CraftaxIronBootstrapEnv,
    "glyphbench/craftax-diamond-bootstrap-v0": CraftaxDiamondBootstrapEnv,
    "glyphbench/craftax-wave-defense-v0": CraftaxWaveDefenseEnv,
    "glyphbench/craftax-build-shelter-v0": CraftaxBuildShelterEnv,
    "glyphbench/craftax-plant-farm-v0": CraftaxPlantFarmEnv,
    "glyphbench/craftax-find-water-v0": CraftaxFindWaterEnv,
    "glyphbench/craftax-find-diamond-v0": CraftaxFindDiamondEnv,
    "glyphbench/craftax-reach-dungeon-v0": CraftaxReachDungeonEnv,
    "glyphbench/craftax-firstday-v0": CraftaxFirstDayEnv,
    "glyphbench/craftax-speedrun-v0": CraftaxSpeedrunEnv,
    # P3 hard transfer subtasks
    "glyphbench/craftax-torchdescend-v0": CraftaxTorchDescendEnv,
    "glyphbench/craftax-survivenight-v0": CraftaxSurviveNightHardEnv,
    "glyphbench/craftax-kiteskeletons-v0": CraftaxKiteSkeletonsEnv,
    "glyphbench/craftax-dark-ambush-v0": CraftaxDarkAmbushEnv,
    "glyphbench/craftax-floor-clear-9hp-v0": CraftaxFloorClear9HpEnv,
    "glyphbench/craftax-spell-only-kill-v0": CraftaxSpellOnlyKillEnv,
    "glyphbench/craftax-descent-gauntlet-v0": CraftaxDescentGauntletEnv,
    "glyphbench/craftax-potion-id-stakes-v0": CraftaxPotionIdStakesEnv,
    "glyphbench/craftax-clear-floor-8gate-v0": CraftaxClearFloor8GateEnv,
    "glyphbench/craftax-surface-to-iron-descend-v0": CraftaxSurfaceToIronDescendEnv,
    "glyphbench/craftax-night-horde-no-shelter-v0": CraftaxNightHordeNoShelterEnv,
    "glyphbench/craftax-xp-attribute-spend-v0": CraftaxXpAttributeSpendEnv,
    "glyphbench/craftax-bow-kite-hard-v0": CraftaxBowKiteHardEnv,
    "glyphbench/craftax-enchant-choice-v0": CraftaxEnchantChoiceEnv,
    "glyphbench/craftax-diamond-gear-descend-v0": CraftaxDiamondGearDescendEnv,
}

_MEMORY_DEFAULT_FALSE = {
    # Compact/reactive combat drills: current viewport plus HUD/inventory
    # carries the useful state, and note-taking mostly adds token overhead.
    "glyphbench/craftax-fightzombie-v0",
    "glyphbench/craftax-fight-zombies-v0",
    "glyphbench/craftax-fight-skeletons-v0",
    "glyphbench/craftax-fight-archers-v0",
    "glyphbench/craftax-fight-spiders-v0",
    "glyphbench/craftax-fight-bats-v0",
    "glyphbench/craftax-bow-kite-v0",
    "glyphbench/craftax-bow-kite-hard-v0",
    "glyphbench/craftax-kiteskeletons-v0",
    "glyphbench/craftax-spell-only-kill-v0",
    "glyphbench/craftax-survivehorde-v0",
    "glyphbench/craftax-wave-defense-v0",
    "glyphbench/craftax-potion-id-stakes-v0",
    "glyphbench/craftax-enchant-choice-v0",
}
_UNKNOWN_MEMORY_DEFAULT_FALSE = _MEMORY_DEFAULT_FALSE - set(_REGISTRATIONS)
if _UNKNOWN_MEMORY_DEFAULT_FALSE:
    raise RuntimeError(
        "unknown Craftax memory-default ids: "
        f"{sorted(_UNKNOWN_MEMORY_DEFAULT_FALSE)}"
    )

for _id, _cls in _REGISTRATIONS.items():
    # Craftax is generally a local-viewport, partially observable game with
    # map/resource/stair/progression information worth preserving. Disable
    # memory only for obvious local combat drills.
    register_env(
        _id,
        _cls,
        default_use_memory=_id not in _MEMORY_DEFAULT_FALSE,
    )
